In [1]:
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  


In [6]:
dataset = pd.read_csv("/home/ponisio7/Dropbox/Christian/Udemy/nuevoiris.csv")

In [7]:
dataset 

sepal.length  sepal.width  petal.length  petal.width  variety
0             5.1          3.5           1.4          0.2        0
1             4.9          3.0           1.4          0.2        0
2             4.7          3.2           1.3          0.2        0
3             4.6          3.1           1.5          0.2        0
4             5.0          3.6           1.4          0.2        0
5             5.4          3.9           1.7          0.4        0
6             4.6          3.4           1.4          0.3        0
7             5.0          3.4           1.5          0.2        0
8             4.4          2.9           1.4          0.2        0
9             4.9          3.1           1.5          0.1        0
10            5.4          3.7           1.5          0.2        0
11            4.8          3.4           1.6          0.2        0
12            4.8          3.0           1.4          0.1        0
13            4.3          3.0           1.1          0.1        0
14            5.8          4.0           1.2          0.2        0
15            5.7          4.4           1.5          0.4        0
16            5.4          3.9           1.3          0.4        0
17            5.1          3.5           1.4          0.3        0
18            5.7          3.8           1.7          0.3        0
19            5.1          3.8           1.5          0.3        0
20            5.4          3.4           1.7          0.2        0
21            5.1          3.7           1.5          0.4        0
22            4.6          3.6           1.0          0.2        0
23            5.1          3.3           1.7          0.5        0
24            4.8          3.4           1.9          0.2        0
25            5.0          3.0           1.6          0.2        0
26            5.0          3.4           1.6          0.4        0
27            5.2          3.5           1.5          0.2        0
28            5.2          3.4           1.4          0.2        0
29            4.7          3.2           1.6          0.2        0
..            ...          ...           ...          ...      ...
120           6.9          3.2           5.7          2.3        2
121           5.6          2.8           4.9          2.0        2
122           7.7          2.8           6.7          2.0        2
123           6.3          2.7           4.9          1.8        2
124           6.7          3.3           5.7          2.1        2
125           7.2          3.2           6.0          1.8        2
126           6.2          2.8           4.8          1.8        2
127           6.1          3.0           4.9          1.8        2
128           6.4          2.8           5.6          2.1        2
129           7.2          3.0           5.8          1.6        2
130           7.4          2.8           6.1          1.9        2
131           7.9          3.8           6.4          2.0        2
132           6.4          2.8           5.6          2.2        2
133           6.3          2.8           5.1          1.5        2
134           6.1          2.6           5.6          1.4        2
135           7.7          3.0           6.1          2.3        2
136           6.3          3.4           5.6          2.4        2
137           6.4          3.1           5.5          1.8        2
138           6.0          3.0           4.8          1.8        2
139           6.9          3.1           5.4          2.1        2
140           6.7          3.1           5.6          2.4        2
141           6.9          3.1           5.1          2.3        2
142           5.8          2.7           5.1          1.9        2
143           6.8          3.2           5.9          2.3        2
144           6.7          3.3           5.7          2.5        2
145           6.7          3.0           5.2          2.3        2
146           6.3          2.5           5.0          1.9        2
147           6.5          3.0           5.2        

In [ ]:
dataset.shape

In [4]:
dataset['variety'].value_counts()

Setosa        50
Virginica     50
Versicolor    50
Name: variety, dtype: int64

In [5]:
#convierte en numerico los valores de la clase 
from sklearn.preprocessing import LabelEncoder

class_le = LabelEncoder()
dataset['variety'] = class_le.fit_transform(dataset['variety'].values)

dataset.to_csv('nuevoiris.csv',index=False)

In [8]:
X = dataset.drop('variety', axis=1)  
y = dataset['variety']  

In [9]:
from sklearn.model_selection import train_test_split #separa los datos de prueba de los de entrenamiento
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.50) 

In [10]:
from sklearn.tree import DecisionTreeClassifier 

classifier = DecisionTreeClassifier()  
classifier.fit(X_train, y_train) 

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [11]:
y_pred = classifier.predict(X_test) 

In [12]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))  
print()
print()
print(classification_report(y_test, y_pred)) 

[[26  0  0]
 [ 0 21  2]
 [ 0  1 25]]


              precision    recall  f1-score   support

           0       1.00      1.00      1.00        26
           1       0.95      0.91      0.93        23
           2       0.93      0.96      0.94        26

   micro avg       0.96      0.96      0.96        75
   macro avg       0.96      0.96      0.96        75
weighted avg       0.96      0.96      0.96        75



In [13]:
accuracy_score(y_test, y_pred)

0.96

In [14]:
#ver el árbol
from sklearn import tree
from sklearn.externals.six import StringIO  
dot_data = StringIO() 
dot_data =tree.export_graphviz(classifier, out_file='tree.dot', feature_names=X.columns)


In [15]:

import pydot 
dot_data = StringIO() 
tree.export_graphviz(classifier, out_file=dot_data) 
graph = pydot.graph_from_dot_data(dot_data.getvalue()) 
graph[0].write_png("tree.png")

